version: '3'

# We pass env var WORKSPACE_ID so we can run multiple instances of solhydra in parallel

services:
  mythril:
    image: rmi7/solhydra_mythril:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/mythril:/app/output/"

  oyente:
    image: rmi7/solhydra_oyente:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/oyente:/app/output/"

  solhint:
    image: rmi7/solhydra_solhint:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/solhint:/app/output/"

  solidity-coverage:
    image: rmi7/solhydra_solidity-coverage:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/solidity-coverage:/app/output/"

  solidity-analyzer:
    image: rmi7/solhydra_solidity-analyzer:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/solidity-analyzer:/app/output/"

  surya:
    image: rmi7/solhydra_surya:1.2
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/surya_graph:/app/output/graph/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/surya_describe:/app/output/describe/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/surya_parse:/app/output/parse/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/surya_ftrace:/app/output/ftrace/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/surya_inheritance:/app/output/inheritance/"

  solium:
    image: rmi7/solhydra_solium:1.0
    volumes:
      - "./.workspaces/workspace${WORKSPACE_ID}/input/:/app/input/"
      - "./.workspaces/workspace${WORKSPACE_ID}/output/solium:/app/output/"
